# Generated by Django 3.2.25 on 2024-11-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_student_scid'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default=12, max_length=254),
            preserve_default=False,
        ),
    ]
